version: '3'
services:
  jenkins:
    build: .
    ports:
      - "8084:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc.yaml"

  jcasc_maven_1:
    build:
      context: .
      dockerfile: Dockerfile

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

volumes:
  jenkins_home:
  nexus-data:
